languages = {
    'EN': {
        'app_name': 'Face Attendance',
        'tab_facerecog': 'Face Recognition',
        'tab_addface': 'Add Face',
        'tab_data': 'Data',
        'fr_notify': 'Notify',
        'lbl_enter': 'Enter',
        'lbl_exit': 'Exit',
        'btn_refresh': 'Refresh',
        'lbl_minface': 'Minimum face',
        'lbl_accuracyTH': 'Accuracy threshold',
        'lblfr_camera': 'Cam',
        'lblfr_button': '',
        'lblfr_console': 'Console',
        'lbl_record': 'Number of images',
        'btn_record': 'Take picture',
        'btn_train': 'Train model',
        'btn_retrain_all': 'Retrain all',
        'lblfr_data_table': 'Data table',
        'btn_show_data': 'Show data',
        'btn_clean_data': 'Clean data',
        'popup_input_name_title': 'Input name',
        'popup_lbl_input_name': 'Enter name',
        'popup_btn_okay': 'Save images',
        'popup_btn_cancel': 'Cancel',
        'lbl_language': 'Language',
        'msg_save_image': 'Saving image to: ',
        'err_name_empty': 'Person name and ID required',
        'msg_gen_face_mask': 'Generating faces with mask',
        'msg_done': 'Done',
        'popup_quit': 'Quit',
        'popup_quit_confirm': 'Do you want to quit?',
        'btn_cam_settings': 'Settings',
        'setting_window_title': 'Settings',
        'lblfr_shift_setting': 'Shift setting',
        'lblfr_cam_setting': 'Camera setting',
        'lbl_chose_cam': 'Choose camera',
        'lbl_shift': 'Working hour from',
        'popup_btn_save': 'Save',
        'lbl_to': 'to',
        'lbl_from': 'From',
        'btn_save_table': 'Save table',
        'lbl_name': 'Name',
        'btn_delete': 'Delete',
        'tts_hello': 'Hello',
        'tts_goodbye': 'Good bye',
        'chkbtn_mute_tts': 'Mute speak notification',
        'fr_employee_edit': 'Edit employee',
        'lblfr_training': 'Training',
        'lbl_employee': 'Employee',
        'btn_change_name': 'Change Name'
    },
    'VN': {
        'app_name': 'Điểm mặt',
        'tab_facerecog': 'Nhận dạng khuôn mặt',
        'tab_addface': 'Thêm khuôn mặt',
        'tab_data': 'Dữ liệu',
        'fr_notify': 'Thông báo',
        'lbl_enter': 'Đi vào',
        'lbl_exit': 'Đi ra',
        'btn_refresh': 'Làm mới',
        'lbl_minface': 'Khuôn mặt tối thiểu',
        'lbl_accuracyTH': 'Ngưỡng độ chính xác',
        'lblfr_camera': 'Cam',
        'lblfr_button': '',
        'lblfr_console': 'Console',
        'lbl_record': 'Số lượng ảnh chụp',
        'btn_record': 'Chụp ảnh',
        'btn_train': 'Train model',
        'btn_retrain_all': 'Train lại model',
        'lblfr_data_table': 'Bảng dữ liệu',
        'btn_show_data': 'Hiển thị dữ liệu',
        'btn_clean_data': 'Làm sạch dữ liệu',
        'popup_input_name_title': 'Tên đầu vào',
        'popup_lbl_input_name': 'Nhập tên',
        'popup_btn_okay': 'Lưu ảnh',
        'popup_btn_cancel': 'Hủy bỏ',
        'lbl_language': 'Ngôn ngữ',
        'msg_save_image': 'Lưu ảnh tại: ',
        'err_name_empty': 'Tên nhân viên hoặc ID trống',
        'msg_gen_face_mask': 'Tạo ảnh có khẩu trang',
        'msg_done': 'Xong',
        'popup_quit': 'Thoát',
        'popup_quit_confirm': 'Bạn có muốn thoát ứng dụng?',
        'btn_cam_settings': 'Cài đặt',
        'setting_window_title': 'Cài đặt',
        'lblfr_shift_setting': 'Ca làm việc',
        'lblfr_cam_setting': 'Camera',
        'lbl_chose_cam': 'Chọn camera',
        'lbl_shift': 'Giờ làm việc từ',
        'popup_btn_save': 'Lưu',
        'lbl_to': 'đến',
        'lbl_from': 'Từ',
        'btn_save_table': 'Lưu bảng',
        'lbl_name': 'Tên',
        'btn_delete': 'Xóa',
        'tts_hello': 'Xin chào',
        'tts_goodbye': 'Tạm biệt',
        'chkbtn_mute_tts': 'Tắt thông báo giọng nói',
        'fr_employee_edit': 'Sửa thông tin nhân viên',
        'lblfr_training': 'Training',
        'lbl_employee': 'Nhân viên',
        'btn_change_name': 'Đổi tên'
    }
}
